# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Resuscikate
tagline:             'A casebook of medicine, science, and obsession.'
description:         'Description'
url:                 https://resuscikate.com
baseurl:             '/jekyll/update'
paginate:            5

# About/contact
author:
  name:              Kate
  url:               
  email:             resuscikate@gmail.com

# Custom vars
version:             1.0.0

# External gems
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - zopfli

# Tagging
tag_page_layout: tag_page
tag_page_dir: tag